// lib/langs/derive.mjs — 上游金数据派生纯函数核（零网络零子进程，可单测）
// sync-langs.mjs 的 CLI 壳只负责取数与写盘；解析/派生/一致性校验全在这。
// 离线不变量：derived.provenance.rev 必须等于 upstream.yaml 里该语言 pin——
// 防"pin 升了没重生成"或"derived 被手改"两类账实不符。

// ---------- tags.scm S-expr 解析（够用即停：只抽捕获归属） ----------
// 产出 [{capture:'definition.class', kind, inside:[kinds], nameKind}]，
// 捕获标签挂在紧邻其前的节点上；inside=该节点的祖先 kind 链（外→内）。
export function parseTags(scm) {
  const toks = scm.match(/\(|\)|@?[^\s()]+|"[^"]*"/g) || [];
  const out = [];
  const stack = []; // 每层 {kind, nameKind}
  let pending = null; // 上一个闭合项（捕获标签的宿主）
  for (const tk of toks) {
    if (tk === '(') { stack.push({ kind: null, nameKind: null }); pending = null; }
    else if (tk === ')') {
      const f = stack.pop();
      // 闭帧时把帧上已记的 nameKind 一并带出去（@name 可能打在子节点）
      const childName = f?.lastChild?.nameKind;
      pending = f ? { kind: f.kind, nameKind: f.nameKind || childName,
        inside: stack.map((s) => s.kind).filter(Boolean) } : null;
      if (stack.length) stack[stack.length - 1].lastChild = pending;
    } else if (tk.startsWith('@')) {
      const cap = tk.slice(1);
      // @name 记到**外围帧**上（name: (identifier) @name 的宿主是子节点，
      // 但 name 字段属于外层 decl 节点）
      const host = pending || (stack.length && stack[stack.length - 1].lastChild);
      if (cap === 'name') {
        const top = stack[stack.length - 1];
        if (top && host) top.nameKind = host.kind;
        continue;
      }
      if (!/^(definition|reference)\./.test(cap) || !host) continue;
      out.push({ capture: cap, kind: host.kind, inside: host.inside,
        nameKind: host.nameKind });
      pending = host;
    } else {
      // 原子项：位置0=kind；field: 前缀不影响——kind 是 '(' 后第一个裸 token
      const top = stack[stack.length - 1];
      if (top && top.kind === null && !tk.endsWith(':') && !tk.startsWith('"'))
        top.kind = tk;
      if (top && top.kind !== null) top.lastChild = { kind: tk, inside: null };
      else pending = { kind: tk, inside: null };
    }
  }
  return out;
}

// ---------- linguist languages.yml → exts ----------
// 只解析钉的语言块：languages.yml 结构浅——LangName: 块内 extensions: 列表
export function linguistExts(yml, langKey) {
  const lines = yml.split('\n');
  let inLang = false, inExts = false;
  const exts = [];
  for (const l of lines) {
    if (/^\S/.test(l)) {                    // 顶层键行
      inLang = l.replace(/["']/g, '').startsWith(langKey + ':');
      inExts = false;
      continue;
    }
    if (!inLang) continue;
    if (/^\s+extensions:/.test(l)) { inExts = true; continue; }
    if (/^\s+\S[^:]*:/.test(l)) { inExts = false; continue; }
    if (inExts) {
      const m = l.match(/^\s+-\s+['"]?(\.[\w.]+)/);
      if (m) exts.push(m[1]);
      else inExts = false;
    }
  }
  return exts.sort();
}

// ---------- 派生物定型 ----------
export function derive(langKey, cfg, scmText, lingYml) {
  const caps = parseTags(scmText);
  const dedup = new Map();
  for (const c of caps) {
    const k = `${c.capture}|${c.kind}|${c.inside.join('>')}`;
    if (!dedup.has(k)) dedup.set(k, { ...c, inside: c.inside });
  }
  const declKinds = [], refKinds = [];
  for (const c of [...dedup.values()].sort((x, y) => x.capture.localeCompare(y.capture)
    || x.kind.localeCompare(y.kind))) {
    const e = { shape: c.capture.split('.')[1], kind: c.kind,
      ...(c.inside.length ? { inside: c.inside } : {}),
      ...(c.nameKind ? { nameKind: c.nameKind } : {}) };
    (c.capture.startsWith('definition.') ? declKinds : refKinds).push(e);
  }
  return { declKinds, refKinds,
    exts: linguistExts(lingYml, cfg.linguist) };
}

export function emitDerived(langKey, cfg, d) {
  return `// <auto-generated by sync-langs.mjs — DO NOT EDIT>
// provenance: ${cfg.grammar}@${cfg.rev} ${cfg.tags}
// 词表声明派生物：手写描述符 <lang>.mjs 消费本件组装 decl 规则；
// 边语义（边去哪）不属上游供给面，仍手写。
export const derived = ${JSON.stringify({
    lang: langKey, upstream: { grammar: cfg.grammar, rev: cfg.rev, tags: cfg.tags },
    exts: d.exts, declKinds: d.declKinds, refKinds: d.refKinds,
  }, null, 2)};
`;
}

// ---------- 离线一致性（门禁层，零网络） ----------
// upstream.yaml pin 对 derived 头注 provenance 对账。
// 返回值按语言给 {state: 'ok'|'stale'|'missing'|'orphan'}：
//   stale=pin 变了没重生成；missing=有 pin 无 derived；orphan=有 derived 无 pin
export function parseUpstreamPins(yamlText) {
  // 够用即停：langs: 节下每语言块的 rev: 字段。结构浅手解不引入 yaml 依赖；
  // 只认 langs: 节（sources.linguist.rev 是上游源 pin 非语言 pin）
  const pins = {};
  let inLangs = false, cur = null;
  for (const l of yamlText.split('\n')) {
    if (/^langs:\s*$/.test(l)) { inLangs = true; continue; }
    if (inLangs && /^\S/.test(l)) break;           // 下一个顶层节 → 出节
    if (!inLangs) continue;
    const m2 = l.match(/^ {2}(?<k>\w+)\s*:\s*$/);
    const mRev = l.match(/^ {4}rev:\s*['"]?(?<v>[0-9a-f]{7,40})['"]?\s*$/);
    if (m2) { cur = m2.groups.k; continue; }
    if (mRev && cur) pins[cur] = mRev.groups.v;
  }
  return pins;
}

export function checkDerivedConsistency(upstreamYamlText, derivedSources) {
  // derivedSources: {lang: 文件全文}
  const pins = parseUpstreamPins(upstreamYamlText);
  const out = {};
  for (const [lang, pin] of Object.entries(pins)) {
    const src = derivedSources[lang];
    if (src == null) { out[lang] = { state: 'missing', pin }; continue; }
    const m = src.match(/^\/\/ provenance: \S+@([0-9a-f]{7,40})/m);
    const rev = m?.[1] || null;
    out[lang] = { state: rev === pin ? 'ok' : 'stale', pin, rev };
  }
  for (const lang of Object.keys(derivedSources))
    if (!(lang in pins)) out[lang] = { state: 'orphan', pin: null };
  return out;
}
