// <auto-generated by sync-langs.mjs — DO NOT EDIT>
// provenance: tree-sitter/tree-sitter-javascript@58404d8cf191d69f2674a8fd507bd5776f46cb11 queries/tags.scm
// 词表声明派生物：手写描述符 <lang>.mjs 消费本件组装 decl 规则；
// 边语义（边去哪）不属上游供给面，仍手写。
export const derived = {
  "lang": "js",
  "upstream": {
    "grammar": "tree-sitter/tree-sitter-javascript",
    "rev": "58404d8cf191d69f2674a8fd507bd5776f46cb11",
    "tags": "queries/tags.scm"
  },
  "exts": [
    "._js",
    ".bones",
    ".cjs",
    ".es",
    ".es6",
    ".frag",
    ".gs",
    ".jake",
    ".javascript",
    ".js",
    ".jsb",
    ".jscad",
    ".jsfl",
    ".jslib",
    ".jsm",
    ".jspre",
    ".jss",
    ".jsx",
    ".mjs",
    ".njs",
    ".pac",
    ".sjs",
    ".ssjs",
    ".xsjs",
    ".xsjslib"
  ],
  "declKinds": [
    {
      "shape": "class",
      "kind": "class",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "_"
        }
      ]
    },
    {
      "shape": "class",
      "kind": "class_declaration",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "_"
        }
      ]
    },
    {
      "shape": "constant",
      "kind": "export_statement",
      "nameKind": "identifier",
      "names": [
        {
          "path": [
            "value",
            "left"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "assignment_expression",
      "names": [
        {
          "path": [
            "left"
          ],
          "kind": "identifier"
        },
        {
          "path": [
            "left",
            "property"
          ],
          "kind": "property_identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "function_declaration",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "function_expression",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "generator_function",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "generator_function_declaration",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "pair",
      "nameKind": "property_identifier",
      "names": [
        {
          "path": [
            "key"
          ],
          "kind": "property_identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "variable_declarator",
      "inside": [
        "lexical_declaration"
      ],
      "nameKind": "identifier",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "function",
      "kind": "variable_declarator",
      "inside": [
        "variable_declaration"
      ],
      "nameKind": "identifier",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "method",
      "kind": "method_definition",
      "nameKind": "property_identifier",
      "names": [
        {
          "path": [
            "name"
          ],
          "kind": "property_identifier"
        }
      ]
    }
  ],
  "refKinds": [
    {
      "shape": "call",
      "kind": "_",
      "inside": [
        "call_expression"
      ]
    },
    {
      "shape": "call",
      "kind": "call_expression",
      "nameKind": "identifier",
      "names": [
        {
          "path": [
            "function"
          ],
          "kind": "identifier"
        }
      ]
    },
    {
      "shape": "class",
      "kind": "new_expression",
      "nameKind": "_",
      "names": [
        {
          "path": [
            "constructor"
          ],
          "kind": "_"
        }
      ]
    }
  ]
};
