// <auto-generated by sync-langs.mjs — DO NOT EDIT>
// provenance: tree-sitter/tree-sitter-python@26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64 queries/tags.scm
// 词表声明派生物：手写描述符 <lang>.mjs 消费本件组装 decl 规则；
// 边语义（边去哪）不属上游供给面，仍手写。
export const derived = {
  "lang": "python",
  "upstream": {
    "grammar": "tree-sitter/tree-sitter-python",
    "rev": "26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64",
    "tags": "queries/tags.scm"
  },
  "exts": [
    ".cgi",
    ".fcgi",
    ".gyp",
    ".gypi",
    ".lmi",
    ".py",
    ".py3",
    ".pyde",
    ".pyi",
    ".pyp",
    ".pyt",
    ".pyw",
    ".rpy",
    ".spec",
    ".tac",
    ".wsgi",
    ".xpy"
  ],
  "declKinds": [
    {
      "shape": "class",
      "kind": "class_definition",
      "nameKind": "identifier"
    },
    {
      "shape": "constant",
      "kind": "assignment",
      "inside": [
        "module",
        "expression_statement"
      ],
      "nameKind": "identifier"
    },
    {
      "shape": "function",
      "kind": "function_definition",
      "nameKind": "identifier"
    }
  ],
  "refKinds": [
    {
      "shape": "call",
      "kind": "call",
      "nameKind": "identifier"
    }
  ]
};
