// <auto-generated by sync-langs.mjs — DO NOT EDIT>
// provenance: tree-sitter/tree-sitter-rust@77a3747266f4d621d0757825e6b11edcbf991ca5 queries/tags.scm
// 词表声明派生物：手写描述符 <lang>.mjs 消费本件组装 decl 规则；
// 边语义（边去哪）不属上游供给面，仍手写。
export const derived = {
  "lang": "rust",
  "upstream": {
    "grammar": "tree-sitter/tree-sitter-rust",
    "rev": "77a3747266f4d621d0757825e6b11edcbf991ca5",
    "tags": "queries/tags.scm"
  },
  "exts": [
    ".rs",
    ".rs.in"
  ],
  "declKinds": [
    {
      "shape": "class",
      "kind": "enum_item",
      "nameKind": "type_identifier"
    },
    {
      "shape": "class",
      "kind": "struct_item",
      "nameKind": "type_identifier"
    },
    {
      "shape": "class",
      "kind": "type_item",
      "nameKind": "type_identifier"
    },
    {
      "shape": "class",
      "kind": "union_item",
      "nameKind": "type_identifier"
    },
    {
      "shape": "function",
      "kind": "function_item",
      "nameKind": "identifier"
    },
    {
      "shape": "interface",
      "kind": "trait_item",
      "nameKind": "type_identifier"
    },
    {
      "shape": "macro",
      "kind": "macro_definition",
      "nameKind": "identifier"
    },
    {
      "shape": "method",
      "kind": "function_item",
      "inside": [
        "declaration_list"
      ],
      "nameKind": "identifier"
    },
    {
      "shape": "module",
      "kind": "mod_item",
      "nameKind": "identifier"
    }
  ],
  "refKinds": [
    {
      "shape": "call",
      "kind": "call_expression",
      "nameKind": "identifier"
    },
    {
      "shape": "call",
      "kind": "macro_invocation",
      "nameKind": "identifier"
    },
    {
      "shape": "implementation",
      "kind": "impl_item",
      "nameKind": "type_identifier"
    }
  ]
};
